---
name: KICS

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ›ï¸ Checkout
      uses: actions/checkout@v3
    - name: ğŸ“¡ run kics Scan
      uses: checkmarx/kics-github-action@v1.7.0
      with:
        path: /
        fail_on: high,medium
        token: ${{ secrets.GITHUB_TOKEN }}
        output_path: myResults/
        ignore_on_exit: results
        enable_comments: true
